build:
	elm make login.elm --output=../python/templates/login.html
	elm make binaryTree.elm --output=../python/static/builds/binaryTree.js

format:
	elm-format login.elm --yes
	elm-format binaryTree.elm --yes